version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - gis_6ban_network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - gis_6ban_static:/data/static/
      - gis_6ban_media:/data/media/

  django:
    image: woong_django:3
    networks:
      - gis_6ban_network
    volumes:
      - gis_6ban_static:/home/Woong_AppAplication/staticfiles/
      - gis_6ban_media:/home/Woong_AppAplication/media/



networks:
  gis_6ban_network:

volumes:
  gis_6ban_static:
  gis_6ban_media: